In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
pasport_df = pd.read_excel('heartDB.xls', sheet_name = 'Паспорт', na_values=['NA'])
sovershen_one_df = pd.read_excel('heartDB.xls', sheet_name = 'Совершен1', na_values=['NA'])
sovershen_two_df = pd.read_excel('heartDB.xls', sheet_name = 'Совершен2', na_values=['NA'])
inspection_df = pd.read_excel('heartDB.xls', sheet_name = 'Обслед', na_values=['NA'])
family_df = pd.read_excel('heartDB.xls', sheet_name = 'Семья', na_values=['NA'])
home_farm_df = pd.read_excel('heartDB.xls', sheet_name = 'Дом хоз', na_values=['NA'])
assessment_of_territories_df = pd.read_excel('heartDB.xls', sheet_name = 'Оценка терр', na_values=['NA'])
physical_activity_df = pd.read_excel('heartDB.xls', sheet_name = 'Физич акт', na_values=['NA'])
ipaq_df = pd.read_excel('heartDB.xls', sheet_name = 'IPAQ', na_values=['NA'])
nutrition_df = pd.read_excel('heartDB.xls', sheet_name = 'Питание', na_values=['NA'])
epoch_two_df = pd.read_excel('heartDB.xls', sheet_name = 'EPOCH2', na_values=['NA'])
nutrition_two_df = pd.read_excel('heartDB.xls', sheet_name = 'Питание2', na_values=['NA'])

In [4]:
#колонки которые будем удалять
# print(nutrition_df.columns['163. Витамин А':'174. Поливитамины'])
print(nutrition_df.columns[161:175])

Index(['161. Витамины в таблетках', '162. Минералы в таблетках',
       '163. Витамин А', '164. Витамин D', '165. Витамин Е', '166. Витамин В',
       '167. Витамин C', '168. Кальций', '169. Железо', '170. Цинк',
       '171. Йод', '172. Магний', '173. Рыбий жир', '174. Поливитамины'],
      dtype='object')

In [28]:
#drop columns
nutrition_df_without_vitamin = nutrition_df.drop(columns=['161. Витамины в таблетках', '162. Минералы в таблетках',
       '163. Витамин А', '164. Витамин D', '165. Витамин Е', '166. Витамин В',
       '167. Витамин C', '168. Кальций', '169. Железо', '170. Цинк',
       '171. Йод', '172. Магний', '173. Рыбий жир', '174. Поливитамины', '184. Добавление соли'])

In [11]:
#values normalization
nutrition_df_without_vitamin.replace(['1. никогда, реже одного раза в месяц', 
                                      '7. 2-3 дн', 
                                      '2. 1-3 мес', 
                                      '3. 1 нед', 
                                      '6. 1 дн',
                                      '4. 2-4 нед', 
                                      '9. >6дн', 
                                      '5. 5-6 нед', 
                                      '8. 4-5 дн',
                                     
                                    ],                                     
                                     [
                                         'никогда, реже одного раза в месяц',
                                         '2-3 дн',
                                          '1-3 мес', 
                                         '1 нед',
                                         '1 дн',
                                           '2-4 нед',
                                          '>6дн', 
                                           '5-6 нед',
                                         '4-5 дн'
                                     ], inplace = True)

In [8]:
#get na
with_na = nutrition_df.isna().sum()
print(with_na.loc[with_na > 0])

163. Витамин А       1572
164. Витамин D       1559
165. Витамин Е       1576
166. Витамин В       1558
167. Витамин C       1543
168. Кальций         1523
169. Железо          1576
170. Цинк            1584
171. Йод             1563
172. Магний          1570
173. Рыбий жир       1563
174. Поливитамины    1124
dtype: int64

In [7]:
nutrition_df.dropna(subset = ['182. Сливочное масло'], inplace = True)

In [12]:
# #string values to number
# nutrition_df.replace(list(nutrition_value_dictionary.keys()), list(nutrition_value_dictionary.values()), inplace= True)

In [30]:
#drop na
nutrition_df_without_vitamin.dropna(inplace=True)

In [31]:
# вывод всех у кого осталось na
with_na = nutrition_df_without_vitamin.isna().sum()
print(with_na.loc[with_na > 0])

Series([], dtype: int64)

In [32]:
#выделение уникальных категорий в таблице
tmp = {}
nutrition_value = []
for col in nutrition_df_without_vitamin.columns[1:]:
    for u in nutrition_df_without_vitamin[col].unique():
        if tmp.get(u, 0) == 0:
            tmp[u] = 0
        else:
            tmp[u] += 1
        
for k in tmp.keys():
    nutrition_value.append(k)

In [33]:
for nv in nutrition_value:
    print(nv)

никогда, реже одного раза в месяц
2-3 дн
1-3 мес
1 нед
1 дн
2-4 нед
>6дн
5-6 нед
4-5 дн

In [9]:
nutrition_value_dictionary = {
    'никогда, реже одного раза в месяц': 0,
    '1-3 мес' : 1,
    '1 нед' : 2,
    '2-4 нед' : 3,
    '5-6 нед' : 4,
    '1 дн' : 5,
    '2-3 дн' : 6,
    '4-5 дн' : 7,
    '>6дн' : 8    
}

In [10]:
print(list(nutrition_value_dictionary.keys()))

['никогда, реже одного раза в месяц', '1-3 мес', '1 нед', '2-4 нед', '5-6 нед', '1 дн', '2-3 дн', '4-5 дн', '>6дн']

In [36]:
#string values to number
nutrition_df_without_vitamin.replace(list(nutrition_value_dictionary.keys()), list(nutrition_value_dictionary.values()), inplace= True)

In [37]:
nutrition_df_without_vitamin.head()

,ID,1. Молоко до 1%,"2. Молоко до 2,5%",3. Молоко более 3%,4. Сгущенка,5. Кефир до 1%,"6. Кефир до 2,5%",7. Кефир более 3%,8. Йогурт до 1%,"9. Йогурт до 2,5%",...,160. Соевый соус,175. Соевое масло,176. Кукурузное масло,177. Растительное масло,178. Подсолнечное масло,179. Рапсовое масло,180. Хлопковое масло,181. Оливковое масло,182. Сливочное масло,183. Питание в ресторанах
0,54-101-001-01,0,0,0,0,0,3,0,0,0,...,0,0,0,0,3,0,0,2,1,0
1,54-602-024-01,0,0,2,0,0,0,0,0,0,...,0,0,0,0,3,0,0,1,3,0
2,54-601-020-01,0,0,5,0,0,0,1,0,0,...,2,0,0,0,5,0,0,0,3,0
3,54-701-021-01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,54-504-035-01,0,1,0,0,2,0,0,0,0,...,0,0,0,0,2,0,0,0,3,0

In [38]:
#save to csv
nutrition_df_without_vitamin.to_csv('nutrition.csv')

In [39]:
#copy data frame
nutrition_new = nutrition_df_without_vitamin

In [40]:
nutrition_new.reset_index(drop=True)

,ID,1. Молоко до 1%,"2. Молоко до 2,5%",3. Молоко более 3%,4. Сгущенка,5. Кефир до 1%,"6. Кефир до 2,5%",7. Кефир более 3%,8. Йогурт до 1%,"9. Йогурт до 2,5%",...,160. Соевый соус,175. Соевое масло,176. Кукурузное масло,177. Растительное масло,178. Подсолнечное масло,179. Рапсовое масло,180. Хлопковое масло,181. Оливковое масло,182. Сливочное масло,183. Питание в ресторанах
0,54-101-001-01,0,0,0,0,0,3,0,0,0,...,0,0,0,0,3,0,0,2,1,0
1,54-602-024-01,0,0,2,0,0,0,0,0,0,...,0,0,0,0,3,0,0,1,3,0
2,54-601-020-01,0,0,5,0,0,0,1,0,0,...,2,0,0,0,5,0,0,0,3,0
3,54-701-021-01,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,54-504-035-01,0,1,0,0,2,0,0,0,0,...,0,0,0,0,2,0,0,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1592,54-102-142-01,0,3,0,0,0,3,3,0,0,...,0,0,1,0,1,0,0,2,3,0
1593,54-503-001-01,0,5,0,0,0,1,0,0,0,...,0,0,0,0,5,0,0,0,0,0
1594,54-501-048-01,0,5,0,0,0,0,0,0,5,...,1,0,0,2,2,0,0,1,0,0
1595,54-501-078-01,0,0,0,0,3,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
1596,54-501-014-02,0,0,0,0,0,3,0,0,0,...,0,0,0,0,2,0,0,1,4,0

# Разбиение по категориям

In [41]:
tmp = []
for i in nutrition_new.index:
    tmp.append(nutrition_new.loc[i,'1. Молоко до 1%':'3. Молоко более 3%'].max())
nutrition_new['milk'] = tmp

In [19]:
nutrition_new.drop(columns=['1. Молоко до 1%', '2. Молоко до 2,5%', '3. Молоко более 3%'], inplace = True)

In [46]:
nutrition_new.describe()

,1. Молоко до 1%,"2. Молоко до 2,5%",3. Молоко более 3%,4. Сгущенка,5. Кефир до 1%,"6. Кефир до 2,5%",7. Кефир более 3%,8. Йогурт до 1%,"9. Йогурт до 2,5%",10. Йогурт более 3%,...,175. Соевое масло,176. Кукурузное масло,177. Растительное масло,178. Подсолнечное масло,179. Рапсовое масло,180. Хлопковое масло,181. Оливковое масло,182. Сливочное масло,183. Питание в ресторанах,milk
count,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,...,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,0.174703,1.814652,0.842830,0.809643,0.594239,1.599249,0.283031,0.183469,0.675642,0.211647,...,0.013776,0.046337,0.575454,2.758297,0.041327,0.008766,0.530369,1.646838,0.286788,2.558547
std,0.800320,2.051214,1.706458,1.411138,1.343570,1.778372,1.000648,0.712071,1.272414,0.784588,...,0.157711,0.356264,1.474120,1.525617,0.358632,0.127334,0.963552,1.774721,0.809039,2.065314
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000
75%,0.000000,3.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,3.000000,0.000000,5.000000
max,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,6.000000,6.000000,6.000000,...,3.000000,5.000000,8.000000,8.000000,6.000000,3.000000,5.000000,8.000000,6.000000,8.000000

In [52]:
# получение названий столбцов с кисломолочкой
tmp_columns = list(nutrition_new.columns[5:11])
tmp_columns.extend(list(nutrition_new.columns[15:17]))
print(tmp_columns)

['5. Кефир до 1%', '6. Кефир до 2,5%', '7. Кефир более 3%', '8. Йогурт до 1%', '9. Йогурт до 2,5%', '10. Йогурт более 3%', '15. Сметана до 15%', '16. Сметана более 20%']

In [57]:
#создание нового столбца с кисломолочкой
tmp = []
for i in nutrition_new.index:
    tmp.append(nutrition_new.loc[i, tmp_columns].max())
nutrition_new['sour_milk'] = tmpnutrition_new.describe()

In [58]:
nutrition_new.describe()

,1. Молоко до 1%,"2. Молоко до 2,5%",3. Молоко более 3%,4. Сгущенка,5. Кефир до 1%,"6. Кефир до 2,5%",7. Кефир более 3%,8. Йогурт до 1%,"9. Йогурт до 2,5%",10. Йогурт более 3%,...,176. Кукурузное масло,177. Растительное масло,178. Подсолнечное масло,179. Рапсовое масло,180. Хлопковое масло,181. Оливковое масло,182. Сливочное масло,183. Питание в ресторанах,milk,sour_milk
count,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,...,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,0.174703,1.814652,0.842830,0.809643,0.594239,1.599249,0.283031,0.183469,0.675642,0.211647,...,0.046337,0.575454,2.758297,0.041327,0.008766,0.530369,1.646838,0.286788,2.558547,3.614277
std,0.800320,2.051214,1.706458,1.411138,1.343570,1.778372,1.000648,0.712071,1.272414,0.784588,...,0.356264,1.474120,1.525617,0.358632,0.127334,0.963552,1.774721,0.809039,2.065314,1.549192
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,3.000000
75%,0.000000,3.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,3.000000,0.000000,5.000000,5.000000
max,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,6.000000,6.000000,6.000000,...,5.000000,8.000000,8.000000,6.000000,3.000000,5.000000,8.000000,6.000000,8.000000,8.000000

In [59]:
# получение названий столбцов с творогом
tmp_columns = list(nutrition_new.columns[11:15])
print(tmp_columns)

['11. Творог до 5%', '12. Творог более 5%', '13. Сырки', '14. Творожники']

In [60]:
#создание нового столбца с творогом
tmp = []
for i in nutrition_new.index:
    tmp.append(nutrition_new.loc[i, tmp_columns].max())
nutrition_new['curd'] = tmp

NameError: name 'tmpnutrition_new' is not defined

In [62]:
nutrition_new.describe()

,1. Молоко до 1%,"2. Молоко до 2,5%",3. Молоко более 3%,4. Сгущенка,5. Кефир до 1%,"6. Кефир до 2,5%",7. Кефир более 3%,8. Йогурт до 1%,"9. Йогурт до 2,5%",10. Йогурт более 3%,...,177. Растительное масло,178. Подсолнечное масло,179. Рапсовое масло,180. Хлопковое масло,181. Оливковое масло,182. Сливочное масло,183. Питание в ресторанах,milk,sour_milk,curd
count,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,...,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,0.174703,1.814652,0.842830,0.809643,0.594239,1.599249,0.283031,0.183469,0.675642,0.211647,...,0.575454,2.758297,0.041327,0.008766,0.530369,1.646838,0.286788,2.558547,3.614277,2.149656
std,0.800320,2.051214,1.706458,1.411138,1.343570,1.778372,1.000648,0.712071,1.272414,0.784588,...,1.474120,1.525617,0.358632,0.127334,0.963552,1.774721,0.809039,2.065314,1.549192,1.368101
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,3.000000,0.000000,0.000000,0.000000,1.000000,0.000000,2.000000,3.000000,2.000000
75%,0.000000,3.000000,0.000000,1.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,3.000000,0.000000,0.000000,1.000000,3.000000,0.000000,5.000000,5.000000,3.000000
max,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,6.000000,6.000000,6.000000,...,8.000000,8.000000,6.000000,3.000000,5.000000,8.000000,6.000000,8.000000,8.000000,6.000000

In [63]:
# получение названий столбцов с сырами
tmp_columns = list(nutrition_new.columns[17:20])
print(tmp_columns)

['17. Сыр мягкий', '18. Сыр до 25%', '19. Сыр более 25%']

In [64]:
#создание нового столбца с сыром
tmp = []
for i in nutrition_new.index:
    tmp.append(nutrition_new.loc[i, tmp_columns].max())
nutrition_new['cheese'] = tmp

In [65]:
# получение названий столбцов с маслом
tmp_columns = list(nutrition_new.columns[20:22])
print(tmp_columns)

['20. Маргарин', '21. Масло бутербр.']

In [ ]:
#создание нового столбца с маслом
tmp = []
for i in nutrition_new.index:
    tmp.append(nutrition_new.loc[i, tmp_columns].max())
nutrition_new[''] = tmp

In [38]:
def groping_nutrition(df, column_numbers, new_column_name):
    tmp_columns = list(df.columns[column_numbers])
    tmp = []
    for i in df.index:
        tmp.append(df.loc[i, tmp_columns].max())
    category_nutrition_df[new_column_name] = tmp

In [28]:
nutrituion_categories_columns = {
    'milk' : [1, 2 ,4],
    'sour_milk' : [5, 6, 7, 8, 9, 10, 15, 16],
    'curd' : [11, 12, 13, 14],
    'cheese' : [17, 18, 19],
    'oil' : [17, 18, 19, 20, 21, 175, 176, 177, 178, 179, 180, 181, 182, 183],
    'fruits' : [23, 24, 25, 26, 27, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    'dried_fruits' : [28, 29],
    'vegetables' : [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86],
    'legumes' : [58, 59, 60, 61, 62],
    'eggs' : [87],
    'meat' : [87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 99, 100, 101, 102, 103, 104, 105, 106],
    'fish' : [97, 98, 99],
    'farinaceous_food' : [109, 110, 111, 112, 115, 116, 141, 142, 143],
    'cereals' : [113, 118, 119, 120, 121, 122, 123],
    'soups' : [124, 125, 126, 127, 128, 129, 130],
    'juices' : [131],
    'tea': [133],
    'coffee' : [132],
    'soda' : [135],
    'water' : [134],
    'alcohol' : [137, 138, 139],
    'sweets' : [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 22, 4] 
}

In [25]:
print(list(range(144, 155)))# + list(range(115, 117)) + list(range(141, 144)))

[144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154]

In [34]:
category_nutrition_df = pd.DataFrame()

In [39]:
category_nutrition_df['user_id'] = nutrition_df.loc[:,'ID']

In [40]:
for key, value in nutrituion_categories_columns.items():
    groping_nutrition(nutrition_df, value, key)

In [41]:
category_nutrition_df.describe()

,milk,sour_milk,curd,cheese,oil,fruits,dried_fruits,vegetables,legumes,eggs,...,farinaceous_food,cereals,soups,juices,tea,coffee,soda,water,alcohol,sweets
count,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,...,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000,1597.000000
mean,2.335629,3.614277,2.149656,3.001252,4.231684,4.541014,1.145272,4.194114,1.330620,2.798998,...,5.270507,2.781465,2.587351,1.483406,5.217282,3.291171,0.170946,5.720100,0.708203,4.316218
std,2.041564,1.549192,1.368101,1.761464,1.259121,1.313265,1.283278,1.087588,1.112538,1.294987,...,1.349636,1.100447,0.976242,1.580507,1.875111,2.554862,0.670882,1.884823,0.951856,1.817023
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,3.000000,1.000000,2.000000,3.000000,4.000000,0.000000,3.000000,1.000000,2.000000,...,5.000000,2.000000,2.000000,0.000000,5.000000,0.000000,0.000000,5.000000,0.000000,3.000000
50%,2.000000,3.000000,2.000000,3.000000,5.000000,5.000000,1.000000,5.000000,1.000000,3.000000,...,6.000000,3.000000,3.000000,1.000000,6.000000,5.000000,0.000000,6.000000,0.000000,5.000000
75%,4.000000,5.000000,3.000000,5.000000,5.000000,5.000000,2.000000,5.000000,2.000000,3.000000,...,6.000000,3.000000,3.000000,3.000000,6.000000,5.000000,0.000000,7.000000,1.000000,6.000000
max,8.000000,8.000000,6.000000,8.000000,8.000000,8.000000,7.000000,8.000000,7.000000,8.000000,...,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000

In [43]:
#save to csv
category_nutrition_df.to_csv('categorical_nutrition_df.csv')

In [87]:
print(nutrition_new.columns[[175, 176, 177, 178, 179, 180, 181, 182, 183]])

IndexError: index 175 is out of bounds for axis 0 with size 174

In [ ]:
groping_nutrition(nutrition_new, list(range())

# Labels

In [3]:
labels = pd.read_excel('heartDB.xls', sheet_name = 'Совершен1', na_values=['NA'], usecols = "A, N, P, R, T, V")

In [8]:
list(['user_id'])+list(labels.columns[2:])

['user_id',
 'ОНМК',
 'Стенокардия, ИБС, инфаркт миокарда',
 'Сердечная недостаточность',
 'Прочие заболевания сердца']

In [9]:
labels.set_axis(list(['user_id'])+list(labels.columns[1:]), axis='columns', inplace = True)

In [12]:
tmp = []
for row in labels.index:
    tmp.append(labels.loc[row, list(labels.columns[1:])].sum())
labels['sum_labels'] = tmp

In [18]:
labels.loc[labels.loc[:,'sum_labels'] > 4]

,user_id,Артериальная гипертензия,ОНМК,"Стенокардия, ИБС, инфаркт миокарда",Сердечная недостаточность,Прочие заболевания сердца,sum_labels
254,54-101-020-01,1,1,1,1,1,5

In [19]:
labels.drop(columns = ['sum_labels'], inplace = True)

In [33]:
labels.isna().sum()

user_id                               0
Артериальная гипертензия              0
ОНМК                                  0
Стенокардия, ИБС, инфаркт миокарда    0
Сердечная недостаточность             0
Прочие заболевания сердца             0
dtype: int64

In [38]:
tmp = []
for row in labels.index:
    tmp.append(list(labels.loc[row, 'Артериальная гипертензия':]))

In [35]:
list(labels.loc[:, 'user_id'])

['54-101-001-01',
 '54-602-024-01',
 '54-601-020-01',
 '54-701-021-01',
 '54-504-035-01',
 '54-504-009-01',
 '54-502-001-01',
 '54-602-040-01',
 '54-504-003-01',
 '54-504-002-01',
 '54-504-032-01',
 '54-504-036-01',
 '54-504-028-01',
 '54-702-018-01',
 '54-502-012-01',
 '54-601-004-02',
 '54-503-018-01',
 '54-502-006-02',
 '54-702-026-01',
 '54-601-056-01',
 '54-601-055-01',
 '54-601-052-01',
 '54-503-004-01',
 '54-503-021-01',
 '54-502-008-01',
 '54-503-006-01',
 '54-601-051-01',
 '54-601-004-01',
 '54-701-024-02',
 '54-701-037-01',
 '54-701-020-01',
 '54-701-035-01',
 '54-701-034-01',
 '54-701-029-01',
 '54-601-030-02',
 '54-601-030-04',
 '54-601-033-01',
 '54-601-033-02',
 '54-601-043-01',
 '54-601-034-02',
 '54-002-015-01',
 '54-601-041-01',
 '54-002-103-01',
 '54-002-172-01',
 '54-602-026-02',
 '54-701-037-02',
 '54-602-035-01',
 '54-602-057-01',
 '54-602-048-01',
 '54-103-001-01',
 '54-602-058-01',
 '54-602-049-01',
 '54-103-002-01',
 '54-103-003-01',
 '54-701-032-01',
 '54-602-051-01',
 '54-602-059-01',
 '54-602-060-01',
 '54-701-033-02',
 '54-602-053-01',
 '54-602-039-01',
 '54-602-062-01',
 '54-602-054-01',
 '54-602-002-01',
 '54-602-038-01',
 '54-602-055-01',
 '54-601-012-02',
 '54-103-004-01',
 '54-103-006-02',
 '54-103-007-01',
 '54-701-033-01',
 '54-601-011-01',
 '54-602-056-01',
 '54-601-013-01',
 '54-701-028-01',
 '54-602-035-02',
 '54-601-016-01',
 '54-601-017-02',
 '54-602-036-01',
 '54-602-034-01',
 '54-602-037-01',
 '54-602-041-01',
 '54-602-042-01',
 '54-602-044-01',
 '54-602-047-01',
 '54-601-009-02',
 '54-601-010-02',
 '54-601-011-02',
 '54-601-015-02',
 '54-601-050-01',
 '54-601-019-01',
 '54-601-005-02',
 '54-601-006-01',
 '54-601-029-01',
 '54-701-019-01',
 '54-601-027-01',
 '54-601-028-02',
 '54-602-030-01',
 '54-602-014-01',
 '54-602-013-01',
 '54-701-024-01',
 '54-601-008-01',
 '54-701-023-01',
 '54-701-022-01',
 '54-701-011-01',
 '54-701-014-01',
 '54-602-006-01',
 '54-701-016-01',
 '54-701-017-01',
 '54-602-033-01',
 '54-602-032-01',
 '54-701-018-01',
 '54-602-005-01',
 '54-602-004-01',
 '54-701-036-01',
 '54-701-031-01',
 '54-701-013-01',
 '54-602-031-01',
 '54-701-039-01',
 '54-701-018-02',
 '54-701-015-01',
 '54-602-026-01',
 '54-701-041-01',
 '54-701-014-02',
 '54-602-008-01',
 '54-701-012-01',
 '54-701-012-02',
 '54-602-009-02',
 '54-602-025-01',
 '54-701-011-02',
 '54-602-010-01',
 '54-701-030-01',
 '54-701-008-01',
 '54-602-015-01',
 '54-102-003-01',
 '54-701-027-01',
 '54-701-026-01',
 '54-701-025-01',
 '54-701-045-01',
 '54-701-046-01',
 '54-701-004-01',
 '54-701-047-01',
 '54-701-005-01',
 '54-701-048-01',
 '54-102-014-02',
 '54-102-021-01',
 '54-102-026-01',
 '54-701-002-01',
 '54-701-003-01',
 '54-701-006-01',
 '54-701-007-01',
 '54-702-036-01',
 '54-702-038-01',
 '54-702-037-01',
 '54-702-004-01',
 '54-702-035-01',
 '54-702-033-01',
 '54-701-009-01',
 '54-701-010-01',
 '54-702-031-01',
 '54-702-027-01',
 '54-702-007-01',
 '54-702-025-01',
 '54-702-008-01',
 '54-702-011-01',
 '54-702-013-01',
 '54-702-024-01',
 '54-702-012-01',
 '54-702-010-01',
 '54-501-057-01',
 '54-501-058-01',
 '54-501-065-01',
 '54-702-022-01',
 '54-501-066-01',
 '54-602-011-01',
 '54-501-067-01',
 '54-501-068-01',
 '54-501-069-01',
 '54-501-071-02',
 '54-601-025-01',
 '54-601-021-02',
 '54-501-072-01',
 '54-501-075-01',
 '54-501-073-01',
 '54-501-076-01',
 '54-103-007-02',
 '54-103-010-01',
 '54-501-055-01',
 '54-103-009-01',
 '54-103-008-01',
 '54-501-080-01',
 '54-501-079-01',
 '54-501-051-01',
 '54-501-056-01',
 '54-501-077-01',
 '54-501-052-01',
 '54-501-053-01',
 '54-501-003-01',
 '54-501-042-01',
 '54-501-044-01',
 '54-501-041-01',
 '54-501-047-01',
 '54-501-045-01',
 '54-102-037-01',
 '54-501-045-02',
 '54-102-051-01',
 '54-501-040-02',
 '54-501-009-01',
 '54-102-072-01',
 '54-501-050-01',
 '54-102-126-01',
 '54-102-033-02',
 '54-501-040-01',
 '54-501-049-01',
 '54-102-206-02',
 '54-501-039-03',
 '54-102-167-02',
 '54-501-009-02',
 '54-102-156-02',
 '54-601-023-01',
 '54-102-054-02',
 '54-501-008-02',
 '54-102-203-01',
 '54-501-007-01',
 '54-501-005-02',
 '54-501-039-01',
 '54-102-139-01',
 '54-501-006-02',
 '54-102-162-01',
 '54-501-006-01',
 '54-102-181-01',
 '54-101-076-01',
 '54-101-012-01',
 '54-701-001-01',
 '54-501-005-01',
 '54-504-011-01',
 '54-501-004-01',
 '54-504-014-01',
 '54-501-003-02',
 '54-504-015-01',
 '54-504-006-01',
 '54-504-017-01',
 '54-504-005-01',
 '54-504-004-01',
 '54-501-039-02',
 '54-504-001-01',
 '54-501-038-02',
 '54-101-089-01',
 '54-101-066-01',
 '54-101-040-01',
 '54-101-036-01',
 '54-101-030-01',
 '54-101-073-01',
 '54-101-014-01',
 '54-101-020-01',
 '54-504-008-01',
 '54-504-033-01',
 '54-504-012-01',
 '54-504-010-01',
 '54-501-062-01',
 '54-504-013-01',
 '54-504-029-01',
 '54-504-027-01',
 '54-501-061-01',
 '54-501-059-02',
 '54-501-059-01',
 '54-504-019-01',
 '54-101-005-01',
 '54-002-192-01',
 '54-002-191-01',
 '54-002-190-02',
 '54-102-168-01',
 '54-102-191-01',
 '54-102-227-02',
 '54-102-202-01',
 '54-002-187-01',
 '54-102-197-02',
 '54-002-184-01',
 '54-002-175-01',
 '54-002-165-01',
 '54-002-163-02',
 '54-002-152-01',
 '54-002-136-02',
 '54-101-011-01',
 '54-101-077-01',
 '54-002-126-01',
 '54-002-121-02',
 '54-002-111-01',
 '54-002-102-02',
 '54-102-318-01',
 '54-002-104-01',
 '54-002-084-01',
 '54-002-080-01',
 '54-002-077-01',
 '54-002-074-02',
 '54-002-064-01',
 '54-002-063-01',
 '54-002-047-01',
 '54-002-043-01',
 '54-002-042-01',
 '54-002-037-01',
 '54-002-034-02',
 '54-002-028-01',
 '54-002-022-02',
 '54-002-019-01',
 '54-002-005-02',
 '54-002-009-02',
 '54-101-082-01',
 '54-101-090-01',
 '54-102-297-01',
 '54-102-288-01',
 '54-504-031-01',
 '54-504-016-01',
 '54-504-018-01',
 '54-504-020-01',
 '54-504-021-01',
 '54-103-014-01',
 '54-103-013-01',
 '54-102-258-01',
 '54-102-238-01',
 '54-102-360-01',
 '54-102-360-02',
 '54-102-281-02',
 '54-103-012-01',
 '54-103-011-01',
 '54-103-015-01',
 '54-102-160-01',
 '54-102-172-01',
 '54-102-171-01',
 '54-102-170-01',
 '54-102-169-01',
 '54-101-015-01',
 '54-102-351-01',
 '54-102-329-01',
 '54-102-352-02',
 '54-102-342-02',
 '54-101-006-01',
 '54-101-091-01',
 '54-101-057-01',
 '54-102-181-02',
 '54-102-184-02',
 '54-102-188-02',
 '54-102-189-02',
 '54-102-030-01',
 '54-102-029-01',
 '54-102-028-01',
 '54-102-027-01',
 '54-103-016-01',
 '54-702-032-01',
 '54-702-032-02',
 '54-101-063-01',
 '54-102-195-01',
 '54-702-033-02',
 '54-504-003-02',
 '54-504-001-02',
 '54-504-012-02',
 '54-101-059-01',
 '54-504-005-02',
 '54-702-035-02',
 '54-102-166-01',
 '54-102-167-01',
 '54-702-031-02',
 '54-702-034-01',
 '54-102-159-01',
 '54-102-158-01',
 '54-102-157-01',
 '54-102-200-01',
 '54-102-198-01',
 '54-102-199-01',
 '54-102-197-01',
 '54-102-196-01',
 '54-602-061-01',
 '54-602-045-01',
 '54-102-156-01',
 '54-102-155-01',
 '54-102-154-01',
 '54-102-153-01',
 '54-102-152-01',
 '54-102-193-01',
 '54-102-192-01',
 '54-102-194-01',
 '54-102-011-01',
 '54-702-030-01',
 '54-702-029-01',
 '54-702-028-01',
 '54-702-026-02',
 '54-102-190-01',
 '54-602-043-01',
 '54-602-050-01',
 '54-102-189-01',
 '54-102-188-01',
 '54-102-187-01',
 '54-602-052-01',
 '54-102-186-01',
 '54-102-185-01',
 '54-102-016-01',
 '54-102-183-01',
 '54-602-046-01',
 '54-102-059-02',
 '54-102-059-01',
 '54-102-058-01',
 '54-102-057-02',
 '54-102-057-01',
 '54-102-184-01',
 '54-102-100-01',
 '54-102-099-01',
 '54-102-182-01',
 '54-102-098-01',
 '54-102-165-01',
 '54-101-072-01',
 '54-102-164-01',
 '54-102-097-01',
 '54-102-163-01',
 '54-102-096-01',
 '54-102-161-01',
 '54-102-015-01',
 '54-504-026-01',
 '54-504-024-01',
 '54-102-014-01',
 '54-102-013-01',
 '54-102-012-01',
 '54-504-025-01',
 '54-504-023-01',
 '54-102-094-01',
 '54-102-001-01',
 '54-102-002-01',
 '54-102-093-01',
 '54-102-002-02',
 '54-102-004-01',
 '54-102-064-01',
 '54-102-062-01',
 '54-102-061-01',
 '54-102-060-01',
 '54-102-046-01',
 '54-102-045-01',
 '54-102-044-01',
 '54-102-043-01',
 '54-103-017-01',
 '54-102-005-01',
 '54-102-006-01',
 '54-103-017-02',
 '54-103-020-02',
 '54-103-020-01',
 '54-102-042-01',
 '54-102-041-01',
 '54-102-040-01',
 '54-504-013-02',
 '54-102-035-01',
 '54-102-039-01',
 '54-102-038-01',
 '54-504-015-02',
 '54-102-036-01',
 '54-504-016-02',
 '54-102-025-02',
 '54-102-095-01',
 '54-102-092-01',
 '54-102-034-01',
 '54-102-033-01',
 '54-102-032-01',
 '54-102-027-02',
 '54-102-031-01',
 '54-102-198-02',
 '54-102-091-01',
 '54-102-007-01',
 '54-102-055-01',
 '54-102-019-01',
 '54-102-018-01',
 '54-102-017-01',
 '54-102-056-01',
 '54-102-054-01',
 '54-102-053-01',
 '54-102-052-01',
 '54-102-090-01',
 '54-102-050-01',
 '54-102-049-01',
 '54-102-048-01',
 '54-102-047-01',
 '54-102-066-01',
 '54-102-065-01',
 '54-102-077-01',
 '54-102-076-01',
 '54-102-075-01',
 '54-102-074-01',
 '54-102-073-01',
 '54-102-071-01',
 '54-102-070-01',
 '54-102-069-01',
 '54-102-067-01',
 '54-102-063-01',
 '54-602-029-01',
 '54-602-028-01',
 '54-602-027-01',
 '54-602-025-02',
 '54-602-023-01',
 '54-602-017-01',
 '54-602-016-01',
 '54-602-022-01',
 '54-602-018-01',
 '54-701-029-02',
 '54-701-028-02',
 '54-701-026-02',
 '54-501-034-01',
 '54-501-035-01',
 '54-501-036-01',
 '54-102-084-01',
 '54-102-085-01',
 '54-102-086-01',
 '54-102-087-01',
 '54-102-087-02',
 '54-504-029-02',
 '54-001-032-01',
 '54-504-023-02',
 '54-102-171-02',
 '54-001-081-01',
 '54-001-082-01',
 '54-001-083-01',
 '54-001-062-01',
 '54-102-194-02',
 '54-001-064-02',
 '54-001-065-01',
 '54-001-066-01',
 '54-001-067-01',
 '54-102-008-01',
 '54-001-068-01',
 '54-001-070-02',
 '54-001-037-01',
 '54-001-017-01',
 '54-001-018-01',
 '54-001-043-01',
 '54-001-039-01',
 '54-001-029-01',
 '54-001-071-01',
 '54-001-072-01',
 '54-001-073-01',
 '54-001-075-01',
 '54-001-078-01',
 '54-001-079-01',
 '54-001-085-01',
 '54-001-086-01',
 '54-001-087-01',
 '54-001-055-01',
 '54-001-057-01',
 '54-001-058-01',
 '54-001-059-01',
 '54-001-060-01',
 '54-001-096-01',
 '54-001-097-02',
 '54-001-079-02',
 '54-001-080-01',
 '54-001-080-02',
 '54-001-105-01',
 '54-102-046-02',
 '54-103-021-01',
 '54-102-068-01',
 '54-001-028-01',
 '54-001-105-02',
 '54-001-105-03',
 '54-102-089-01',
 '54-001-106-01',
 '54-001-098-01',
 '54-001-098-02',
 '54-001-100-01',
 '54-001-101-01',
 '54-001-102-01',
 '54-001-102-02',
 '54-001-103-01',
 '54-001-074-01',
 '54-001-088-01',
 '54-001-091-01',
 '54-001-092-01',
 '54-102-088-01',
 '54-001-093-01',
 '54-001-094-01',
 '54-001-095-01',
 '54-001-095-02',
 '54-001-104-01',
 '54-001-036-01',
 '54-001-035-01',
 '54-001-034-01',
 '54-001-033-01',
 '54-001-054-01',
 '54-001-053-01',
 '54-001-052-01',
 '54-001-051-01',
 '54-001-049-01',
 '54-001-047-01',
 '54-001-046-01',
 '54-001-045-01',
 '54-001-044-01',
 '54-102-170-02',
 '54-102-158-02',
 '54-102-155-02',
 '54-002-088-01',
 '54-102-199-02',
 '54-002-089-01',
 '54-102-008-02',
 '54-602-012-01',
 '54-702-021-01',
 '54-502-014-01',
 '54-502-016-01',
 '54-502-017-01',
 '54-502-017-02',
 '54-502-018-01',
 '54-002-090-01',
 '54-002-101-01',
 '54-503-005-01',
 '54-503-007-01',
 '54-503-008-01',
 '54-503-009-01',
 '54-503-010-02',
 '54-001-027-01',
 '54-503-011-01',
 '54-503-012-01',
 '54-503-013-01',
 '54-001-026-01',
 '54-002-107-01',
 '54-001-056-01',
 '54-002-107-02',
 '54-102-093-02',
 '54-001-031-01',
 '54-001-038-01',
 '54-002-108-01',
 '54-503-017-01',
 '54-001-097-01',
 '54-001-050-01',
 '54-503-018-02',
 '54-102-066-02',
 '54-001-048-01',
 '54-001-065-02',
 '54-001-082-02',
 '54-602-001-01',
 '54-602-004-02',
 '54-001-020-01',
 '54-503-020-01',
 '54-001-084-01',
 '54-002-102-01',
 '54-002-105-01',
 '54-102-051-02',
 '54-002-106-01',
 '54-002-106-02',
 '54-102-017-02',
 '54-001-090-01',
 '54-102-009-01',
 '54-102-018-02',
 '54-102-009-02',
 '54-102-095-02',
 '54-001-025-01',
 '54-102-065-02',
 '54-002-109-01',
 '54-002-109-02',
 '54-002-110-01',
 '54-002-081-01',
 '54-002-082-01',
 '54-002-083-01',
 '54-002-085-01',
 '54-102-010-01',
 '54-002-086-01',
 '54-504-028-02',
 '54-504-022-01',
 '54-002-087-01',
 '54-002-093-02',
 '54-504-030-01',
 '54-504-034-01',
 '54-504-034-02',
 '54-002-073-01',
 '54-002-074-01',
 '54-504-035-02',
 '54-504-033-02',
 '54-504-036-02',
 '54-002-039-01',
 '54-002-040-01',
 '54-002-041-01',
 '54-002-044-01',
 '54-002-045-01',
 '54-002-045-02',
 '54-002-046-01',
 '54-002-007-01',
 '54-002-048-01',
 '54-002-049-01',
 '54-002-006-01',
 '54-002-005-01',
 '54-002-004-01',
 '54-002-003-01',
 '54-002-002-01',
 '54-002-070-01',
 '54-002-069-02',
 '54-002-069-01',
 '54-002-068-01',
 '54-002-067-01',
 '54-002-066-01',
 '54-002-065-01',
 '54-002-063-02',
 '54-002-055-01',
 '54-002-054-02',
 '54-002-054-01',
 '54-002-076-01',
 '54-002-059-01',
 '54-002-060-01',
 '54-002-060-02',
 '54-002-061-01',
 '54-002-061-02',
 '54-002-062-01',
 '54-002-035-01',
 '54-002-036-01',
 '54-002-038-01',
 '54-002-072-01',
 '54-002-075-01',
 '54-001-006-03',
 '54-101-023-01',
 '54-101-022-01',
 '54-101-021-01',
 '54-101-019-01',
 '54-101-018-01',
 '54-101-017-01',
 '54-101-016-01',
 '54-101-013-01',
 '54-101-010-01',
 '54-101-009-02',
 '54-101-009-01',
 '54-101-008-01',
 '54-101-007-01',
 '54-101-006-02',
 '54-101-004-01',
 '54-101-003-01',
 '54-101-002-01',
 '54-101-002-02',
 '54-101-039-01',
 '54-101-038-01',
 '54-101-037-01',
 '54-101-035-01',
 '54-101-034-01',
 '54-101-033-01',
 '54-001-024-01',
 '54-102-020-01',
 '54-102-044-02',
 '54-102-039-02',
 '54-102-036-02',
 '54-102-022-01',
 '54-102-023-01',
 '54-102-023-02',
 '54-102-024-01',
 '54-102-025-01',
 '54-001-005-01',
 '54-001-004-01',
 '54-001-003-01',
 '54-001-002-01',
 '54-001-001-01',
 '54-502-004-01',
 '54-502-009-01',
 '54-502-011-01',
 '54-002-071-01',
 '54-101-027-01',
 '54-101-028-01',
 '54-001-012-01',
 '54-101-029-01',
 '54-101-029-02',
 '54-101-031-01',
 '54-101-032-01',
 '54-002-016-01',
 '54-002-001-01',
 '54-001-013-01',
 '54-002-021-01',
 '54-002-020-01',
 '54-002-018-01',
 '54-002-017-01',
 '54-001-014-01',
 '54-001-016-01',
 '54-001-046-02',
 '54-001-048-02',
 '54-001-040-02',
 '54-001-025-02',
 '54-001-011-01',
 '54-001-010-01',
 '54-001-009-01',
 '54-001-008-01',
 '54-001-007-01',
 '54-002-094-01',
 '54-002-095-01',
 '54-002-095-02',
 '54-002-096-01',
 '54-002-097-01',
 '54-002-098-01',
 '54-002-099-01',
 '54-002-100-01',
 '54-002-077-02',
 '54-502-019-01',
 '54-502-020-01',
 '54-502-022-01',
 '54-503-003-01',
 '54-002-078-01',
 '54-002-079-01',
 '54-002-091-01',
 '54-002-092-01',
 '54-002-092-02',
 '54-002-093-01',
 '54-002-012-01',
 '54-001-023-01',
 '54-002-014-01',
 '54-002-013-01',
 '54-002-034-01',
 '54-002-008-01',
 '54-002-009-01',
 '54-001-015-01',
 '54-002-010-01',
 '54-002-011-01',
 '54-001-021-01',
 '54-001-089-01',
 '54-001-006-02',
 '54-001-052-02',
 '54-602-007-01',
 '54-602-002-02',
 '54-001-030-01',
 '54-001-057-02',
 '54-602-005-02',
 '54-001-066-02',
 '54-602-006-02',
 '54-001-068-02',
 '54-001-090-02',
 '54-001-005-02',
 '54-102-337-01',
 '54-101-024-01',
 '54-102-338-01',
 '54-101-025-01',
 '54-102-338-02',
 '54-101-026-01',
 '54-102-339-01',
 '54-101-047-01',
 '54-102-340-01',
 '54-101-048-01',
 '54-102-341-01',
 '54-101-049-01',
 '54-102-342-01',
 '54-101-053-01',
 '54-102-343-01',
 '54-101-054-01',
 '54-102-344-01',
 '54-101-050-01',
 '54-101-051-01',
 '54-102-345-01',
 '54-101-052-01',
 '54-101-041-01',
 '54-101-042-01',
 '54-101-043-01',
 '54-101-044-01',
 '54-101-045-01',
 '54-101-046-01',
 '54-101-065-01',
 '54-101-067-01',
 '54-101-068-01',
 '54-001-076-01',
 '54-602-009-01',
 '54-602-019-01',
 '54-001-107-01',
 '54-001-042-01',
 '54-001-041-01',
 '54-001-006-01',
 '54-602-003-01',
 '54-001-064-01',
 '54-001-063-01',
 '54-001-061-01',
 '54-001-069-01',
 '54-001-019-01',
 '54-001-022-01',
 '54-102-348-01',
 '54-102-349-01',
 '54-101-031-02',
 '54-101-052-02',
 '54-101-055-01',
 '54-101-056-01',
 '54-101-060-01',
 '54-101-061-01',
 '54-101-062-01',
 '54-101-064-01',
 '54-101-068-02',
 '54-101-069-01',
 '54-101-070-01',
 '54-101-071-01',
 '54-101-074-01',
 '54-101-075-01',
 '54-101-078-01',
 '54-101-079-01',
 '54-101-080-01',
 '54-101-080-02',
 '54-101-081-01',
 '54-103-018-01',
 '54-103-024-01',
 '54-102-180-01',
 '54-102-179-01',
 '54-002-029-01',
 '54-002-027-01',
 '54-002-026-01',
 '54-002-025-01',
 '54-102-178-01',
 '54-102-177-01',
 '54-102-176-01',
 '54-102-175-01',
 '54-102-174-01',
 '54-102-173-01',
 '54-102-083-01',
 '54-102-335-02',
 '54-001-036-02',
 '54-103-023-01',
 '54-103-022-02',
 '54-103-022-01',
 '54-103-030-01',
 '54-103-029-01',
 '54-103-028-01',
 '54-103-026-01',
 '54-103-025-01',
 '54-102-358-02',
 '54-102-356-02',
 '54-102-205-02',
 '54-102-320-01',
 '54-102-303-01',
 '54-102-304-01',
 '54-102-304-02',
 '54-102-305-01',
 '54-102-306-01',
 '54-102-306-02',
 '54-102-307-01',
 '54-102-353-01',
 '54-102-354-01',
 '54-102-354-02',
 '54-102-355-01',
 '54-102-356-01',
 '54-102-318-02',
 '54-102-319-01',
 '54-102-325-01',
 '54-102-326-01',
 '54-102-327-01',
 '54-102-328-01',
 '54-102-308-01',
 '54-102-352-01',
 '54-102-345-02',
 '54-102-211-01',
 '54-102-212-01',
 '54-102-212-02',
 '54-102-213-01',
 '54-102-214-01',
 '54-102-214-02',
 '54-102-215-01',
 '54-102-216-01',
 '54-102-220-01',
 '54-102-336-01',
 '54-102-223-01',
 '54-102-224-01',
 '54-102-224-02',
 '54-102-225-01',
 '54-102-219-01',
 '54-102-226-01',
 '54-102-227-01',
 '54-102-330-01',
 '54-102-217-01',
 '54-102-331-01',
 '54-102-331-02',
 '54-102-332-01',
 '54-002-033-01',
 '54-102-333-01',
 '54-102-334-01',
 '54-102-221-01',
 '54-102-222-01',
 '54-102-222-02',
 '54-102-236-01',
 '54-002-032-01',
 '54-002-030-01',
 '54-002-168-01',
 '54-002-167-01',
 '54-002-166-02',
 '54-002-193-01',
 '54-002-190-01',
 '54-002-189-01',
 '54-002-188-01',
 '54-002-186-01',
 '54-501-022-01',
 '54-002-185-02',
 '54-002-185-01',
 '54-002-183-01',
 '54-002-182-01',
 '54-501-021-01',
 '54-501-020-01',
 '54-002-181-01',
 '54-002-180-01',
 '54-501-019-01',
 '54-002-159-02',
 '54-002-159-01',
 '54-002-158-01',
 '54-002-179-01',
 '54-501-018-01',
 '54-002-178-01',
 '54-002-177-01',
 '54-002-176-01',
 '54-002-174-01',
 '54-501-016-01',
 '54-002-173-01',
 '54-002-171-01',
 '54-501-013-01',
 '54-002-170-01',
 '54-002-169-01',
 '54-002-150-01',
 '54-002-149-01',
 ...]

In [36]:
labels_one_hote = pd.DataFrame()

In [37]:
labels_one_hote['user_id'] = list(labels.loc[:, 'user_id'])

In [39]:
labels_one_hote['labels'] = tmp

In [53]:
type(labels_one_hote.loc[0,'labels'])

list

In [40]:
labels_one_hote.to_csv('labels.csv')

In [42]:
pasport_df = pd.read_excel('heartDB.xls', sheet_name = 'Паспорт', na_values=['NA'])

In [47]:
pasport_df.dropna(inplace = True)

In [48]:
pasport_df.head()

              ID  Место проживания 1-город 2-село Дата рождения  Возраст
0  54-101-001-01                                1    23.08.1961       54
1  54-602-024-01                                2    17.06.1947       69
2  54-601-020-01                                2    03.01.1961       55
3  54-701-021-01                                2    01.01.1962       54
4  54-504-035-01                                2    29.01.1963       54

In [50]:
tmp_df = pd.DataFrame()
tmp_df['user_id'] = list(pasport_df.loc[:, 'ID'])
tmp_df['age'] = list(pasport_df.loc[:, 'Возраст'])
tmp_df['place_of_living'] = list(pasport_df.loc[:, 'Место проживания 1-город 2-село'])

In [51]:
tmp_df.to_csv('pasport_df.csv')